// billing 计费服务的 gRPC 契约（控制面）。
//
// 状态机（bills 表 reserve 行）：
//
//	Reserve(原子扣减+落库) → [pending]
//	  ── ReportUsage(写 usage_reported_at 持久 marker) → [pending + marker]
//	        ── Settle(幂等) → [settled]（写 settle 行，delta 冲正 Redis）
//	  ── Reverse(幂等) → [reversed]（Redis 退回预扣）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveCode int32

const (
	ReserveCode_RESERVE_OK           ReserveCode = 0
	ReserveCode_RESERVE_INSUFFICIENT ReserveCode = 1 // 余额不足
	ReserveCode_RESERVE_DUPLICATE    ReserveCode = 2 // 已有同 request_id 预占（幂等重放）
	ReserveCode_RESERVE_SUB_QUOTA    ReserveCode = 3 // 订阅额度不足（每 N 小时滚动刷新，M9）
)

// Enum value maps for ReserveCode.
var (
	ReserveCode_name = map[int32]string{
		0: "RESERVE_OK",
		1: "RESERVE_INSUFFICIENT",
		2: "RESERVE_DUPLICATE",
		3: "RESERVE_SUB_QUOTA",
	}
	ReserveCode_value = map[string]int32{
		"RESERVE_OK":           0,
		"RESERVE_INSUFFICIENT": 1,
		"RESERVE_DUPLICATE":    2,
		"RESERVE_SUB_QUOTA":    3,
	}
)

func (x ReserveCode) Enum() *ReserveCode {
	p := new(ReserveCode)
	*p = x
	return p
}

func (x ReserveCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReserveCode) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_v1_billing_proto_enumTypes[0].Descriptor()
}

func (ReserveCode) Type() protoreflect.EnumType {
	return &file_billing_v1_billing_proto_enumTypes[0]
}

func (x ReserveCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReserveCode.Descriptor instead.
func (ReserveCode) EnumDescriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

type ReserveRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // gateway 生成（幂等键或 uuid），全局唯一
	TenantId            int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ApiKeyId            int64                  `protobuf:"varint,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ProviderId          int64                  `protobuf:"varint,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // router 选出的 provider；M5 前可为 0
	Model               string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	EstPromptTokens     int64                  `protobuf:"varint,6,opt,name=est_prompt_tokens,json=estPromptTokens,proto3" json:"est_prompt_tokens,omitempty"`             // gateway 对输入消息的估算
	MaxCompletionTokens int64                  `protobuf:"varint,7,opt,name=max_completion_tokens,json=maxCompletionTokens,proto3" json:"max_completion_tokens,omitempty"` // 可选输出上限；0 表示不限制
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReserveRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ReserveRequest) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *ReserveRequest) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *ReserveRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReserveRequest) GetEstPromptTokens() int64 {
	if x != nil {
		return x.EstPromptTokens
	}
	return 0
}

func (x *ReserveRequest) GetMaxCompletionTokens() int64 {
	if x != nil {
		return x.MaxCompletionTokens
	}
	return 0
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReserveCode            `protobuf:"varint,1,opt,name=code,proto3,enum=billing.v1.ReserveCode" json:"code,omitempty"`
	BillId        int64                  `protobuf:"varint,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`                   // reserve 行 id
	BalanceAfter  int64                  `protobuf:"varint,3,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"` // 预占后的余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveResponse) GetCode() ReserveCode {
	if x != nil {
		return x.Code
	}
	return ReserveCode_RESERVE_OK
}

func (x *ReserveResponse) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *ReserveResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

type ReportUsageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BillId           int64                  `protobuf:"varint,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,4,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReportUsageRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *ReportUsageRequest) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ReportUsageRequest) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type ReportUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ReportUsageResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BillId        int64                  `protobuf:"varint,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *SettleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettleRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settled       bool                   `protobuf:"varint,1,opt,name=settled,proto3" json:"settled,omitempty"`
	DeltaQuota    int64                  `protobuf:"varint,2,opt,name=delta_quota,json=deltaQuota,proto3" json:"delta_quota,omitempty"` // 实际 - 预扣（正补扣 / 负退回）
	BalanceAfter  int64                  `protobuf:"varint,3,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *SettleResponse) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *SettleResponse) GetDeltaQuota() int64 {
	if x != nil {
		return x.DeltaQuota
	}
	return 0
}

func (x *SettleResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

type ReverseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BillId        int64                  `protobuf:"varint,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 对账冲正/上游故障/客户端断连等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ReverseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReverseRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *ReverseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reversed      bool                   `protobuf:"varint,1,opt,name=reversed,proto3" json:"reversed,omitempty"`
	RefundQuota   int64                  `protobuf:"varint,2,opt,name=refund_quota,json=refundQuota,proto3" json:"refund_quota,omitempty"` // 退回的预扣额度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *ReverseResponse) GetReversed() bool {
	if x != nil {
		return x.Reversed
	}
	return false
}

func (x *ReverseResponse) GetRefundQuota() int64 {
	if x != nil {
		return x.RefundQuota
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyHash    string                 `protobuf:"bytes,1,opt,name=api_key_hash,json=apiKeyHash,proto3" json:"api_key_hash,omitempty"` // SHA-256(key)，明文 sk- 永不跨服务传递
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateAPIKeyRequest) GetApiKeyHash() string {
	if x != nil {
		return x.ApiKeyHash
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ApiKeyId      int64                  `protobuf:"varint,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetApiKeyId() int64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *ValidateAPIKeyResponse) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type RebuildBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBalanceRequest) Reset() {
	*x = RebuildBalanceRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBalanceRequest) ProtoMessage() {}

func (x *RebuildBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBalanceRequest.ProtoReflect.Descriptor instead.
func (*RebuildBalanceRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{12}
}

func (x *RebuildBalanceRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type RebuildBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"` // 重建后的余额（投影）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBalanceResponse) Reset() {
	*x = RebuildBalanceResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBalanceResponse) ProtoMessage() {}

func (x *RebuildBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBalanceResponse.ProtoReflect.Descriptor instead.
func (*RebuildBalanceResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{13}
}

func (x *RebuildBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_billing_v1_billing_proto protoreflect.FileDescriptor

const file_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/billing.proto\x12\n" +
	"billing.v1\"\x81\x02\n" +
	"\x0eReserveRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\x03R\bapiKeyId\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\x03R\n" +
	"providerId\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12*\n" +
	"\x11est_prompt_tokens\x18\x06 \x01(\x03R\x0festPromptTokens\x122\n" +
	"\x15max_completion_tokens\x18\a \x01(\x03R\x13maxCompletionTokens\"|\n" +
	"\x0fReserveResponse\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.billing.v1.ReserveCodeR\x04code\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\x03R\x06billId\x12#\n" +
	"\rbalance_after\x18\x03 \x01(\x03R\fbalanceAfter\"\x9e\x01\n" +
	"\x12ReportUsageRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\x03R\x06billId\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x04 \x01(\x03R\x10completionTokens\"1\n" +
	"\x13ReportUsageResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"G\n" +
	"\rSettleRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\x03R\x06billId\"p\n" +
	"\x0eSettleResponse\x12\x18\n" +
	"\asettled\x18\x01 \x01(\bR\asettled\x12\x1f\n" +
	"\vdelta_quota\x18\x02 \x01(\x03R\n" +
	"deltaQuota\x12#\n" +
	"\rbalance_after\x18\x03 \x01(\x03R\fbalanceAfter\"`\n" +
	"\x0eReverseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\abill_id\x18\x02 \x01(\x03R\x06billId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"P\n" +
	"\x0fReverseResponse\x12\x1a\n" +
	"\breversed\x18\x01 \x01(\bR\breversed\x12!\n" +
	"\frefund_quota\x18\x02 \x01(\x03R\vrefundQuota\"0\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"9\n" +
	"\x15ValidateAPIKeyRequest\x12 \n" +
	"\fapi_key_hash\x18\x01 \x01(\tR\n" +
	"apiKeyHash\"i\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\x03R\bapiKeyId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\"4\n" +
	"\x15RebuildBalanceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\"2\n" +
	"\x16RebuildBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance*e\n" +
	"\vReserveCode\x12\x0e\n" +
	"\n" +
	"RESERVE_OK\x10\x00\x12\x18\n" +
	"\x14RESERVE_INSUFFICIENT\x10\x01\x12\x15\n" +
	"\x11RESERVE_DUPLICATE\x10\x02\x12\x15\n" +
	"\x11RESERVE_SUB_QUOTA\x10\x032\xa8\x04\n" +
	"\x0eBillingService\x12B\n" +
	"\aReserve\x12\x1a.billing.v1.ReserveRequest\x1a\x1b.billing.v1.ReserveResponse\x12N\n" +
	"\vReportUsage\x12\x1e.billing.v1.ReportUsageRequest\x1a\x1f.billing.v1.ReportUsageResponse\x12?\n" +
	"\x06Settle\x12\x19.billing.v1.SettleRequest\x1a\x1a.billing.v1.SettleResponse\x12B\n" +
	"\aReverse\x12\x1a.billing.v1.ReverseRequest\x1a\x1b.billing.v1.ReverseResponse\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.billing.v1.GetBalanceRequest\x1a\x1e.billing.v1.GetBalanceResponse\x12W\n" +
	"\x0eValidateAPIKey\x12!.billing.v1.ValidateAPIKeyRequest\x1a\".billing.v1.ValidateAPIKeyResponse\x12W\n" +
	"\x0eRebuildBalance\x12!.billing.v1.RebuildBalanceRequest\x1a\".billing.v1.RebuildBalanceResponseBEZCgithub.com/frostloom/ai-gateway/internal/proto/billing/v1;billingv1b\x06proto3"

var (
	file_billing_v1_billing_proto_rawDescOnce sync.Once
	file_billing_v1_billing_proto_rawDescData []byte
)

func file_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)))
	})
	return file_billing_v1_billing_proto_rawDescData
}

var file_billing_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_billing_v1_billing_proto_goTypes = []any{
	(ReserveCode)(0),               // 0: billing.v1.ReserveCode
	(*ReserveRequest)(nil),         // 1: billing.v1.ReserveRequest
	(*ReserveResponse)(nil),        // 2: billing.v1.ReserveResponse
	(*ReportUsageRequest)(nil),     // 3: billing.v1.ReportUsageRequest
	(*ReportUsageResponse)(nil),    // 4: billing.v1.ReportUsageResponse
	(*SettleRequest)(nil),          // 5: billing.v1.SettleRequest
	(*SettleResponse)(nil),         // 6: billing.v1.SettleResponse
	(*ReverseRequest)(nil),         // 7: billing.v1.ReverseRequest
	(*ReverseResponse)(nil),        // 8: billing.v1.ReverseResponse
	(*GetBalanceRequest)(nil),      // 9: billing.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),     // 10: billing.v1.GetBalanceResponse
	(*ValidateAPIKeyRequest)(nil),  // 11: billing.v1.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 12: billing.v1.ValidateAPIKeyResponse
	(*RebuildBalanceRequest)(nil),  // 13: billing.v1.RebuildBalanceRequest
	(*RebuildBalanceResponse)(nil), // 14: billing.v1.RebuildBalanceResponse
}
var file_billing_v1_billing_proto_depIdxs = []int32{
	0,  // 0: billing.v1.ReserveResponse.code:type_name -> billing.v1.ReserveCode
	1,  // 1: billing.v1.BillingService.Reserve:input_type -> billing.v1.ReserveRequest
	3,  // 2: billing.v1.BillingService.ReportUsage:input_type -> billing.v1.ReportUsageRequest
	5,  // 3: billing.v1.BillingService.Settle:input_type -> billing.v1.SettleRequest
	7,  // 4: billing.v1.BillingService.Reverse:input_type -> billing.v1.ReverseRequest
	9,  // 5: billing.v1.BillingService.GetBalance:input_type -> billing.v1.GetBalanceRequest
	11, // 6: billing.v1.BillingService.ValidateAPIKey:input_type -> billing.v1.ValidateAPIKeyRequest
	13, // 7: billing.v1.BillingService.RebuildBalance:input_type -> billing.v1.RebuildBalanceRequest
	2,  // 8: billing.v1.BillingService.Reserve:output_type -> billing.v1.ReserveResponse
	4,  // 9: billing.v1.BillingService.ReportUsage:output_type -> billing.v1.ReportUsageResponse
	6,  // 10: billing.v1.BillingService.Settle:output_type -> billing.v1.SettleResponse
	8,  // 11: billing.v1.BillingService.Reverse:output_type -> billing.v1.ReverseResponse
	10, // 12: billing.v1.BillingService.GetBalance:output_type -> billing.v1.GetBalanceResponse
	12, // 13: billing.v1.BillingService.ValidateAPIKey:output_type -> billing.v1.ValidateAPIKeyResponse
	14, // 14: billing.v1.BillingService.RebuildBalance:output_type -> billing.v1.RebuildBalanceResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_billing_v1_billing_proto_init() }
func file_billing_v1_billing_proto_init() {
	if File_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_billing_v1_billing_proto_depIdxs,
		EnumInfos:         file_billing_v1_billing_proto_enumTypes,
		MessageInfos:      file_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_billing_v1_billing_proto = out.File
	file_billing_v1_billing_proto_goTypes = nil
	file_billing_v1_billing_proto_depIdxs = nil
}
